modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Viola-Siemens/ECNU-Minecraft-Mod-Template/issues"

[[mods]]
modId="disgusted_creature"
version="${file.jarVersion}"
displayName="Disgusted_Creature"
credits="Woeful"
authors="Woeful"
logoFile="logo.png"
description='''
You may want some unforgettable experiences &
Make ECNUMC Great Again!!!
'''

[[dependencies.disgusted_creature]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.disgusted_creature]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"